CREATE TABLE students (
 id INT NOT NULL AUTO_INCREMENT,
 lastname VARCHAR(20) NOT NULL,
 firstname VARCHAR(20) NOT NULL,
 email VARCHAR(50) NOT NULL,
 age SMALLINT NOT NULL,
 ssn VARCHAR(10) NOT NULL UNIQUE,
 primary key (id)
 );
